version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run https://api.getpostman.com/collections/13114566-f5d0ec0b-0dc8-4f7a-9e6d-0374de15ff55?apikey=PMAK-5f99be4681e18f003de4e14c-1cca68d8a09c5f289f15c2cbab65a8638c -r junit

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: '02postman/newman' # Location of the reports
